// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
// ENV_FILE elige la base igual que en scripts/ (por defecto staging, vía .env.local).
config({ path: process.env.ENV_FILE ?? ".env.local" });

import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // En Prisma 7 el comando de seed se declara aquí, no en el bloque
    // "prisma": { "seed": ... } de package.json (ese formato quedó obsoleto).
    // Esto es lo que ejecuta `npx prisma db seed`.
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
